#!/bin/sh

posts="$(~/scripts/cmd/garf +dir 'posts' || exit 1)"
cd "$posts" || exit 1

if [ "$1" = '--count' ] || [ "$1" = '-c' ]; then
    count="$(find '.' -name "date" | wc -l)"
    echo "Count: $count"
fi

for post in *; do
    if [ ! -f "$post/date" ]; then
        echo "Post id: $post"
        ~/scripts/cmd/garf date "$post" || exit "$?"
    fi
done


