#!/bin/sh

posts="$HOME/pics/garfeo/posts"

id="$1"
if [ ! "$id" ]; then
    echo 'garf date: no post id given'
    exit 1
fi

if [ ! -d "$posts/$id" ]; then
    echo 'garf date: post does not exist with that id'
    exit 1
fi
if [ -f "$posts/$id/date" ]; then
    echo 'garf date: post already has date file'
    exit 1
fi

~/scripts/cmd/garf find -p "$1" || exit 1

printf 'Enter full date (yyyy-mm-dd): '
read -r date

if ! expr "$date" : '^[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}$' > /dev/null; then
    echo 'garf date: full date must be yyyy-mm-dd format'
    exit 1
fi

echo "$date" >> "$posts/$id/date"
echo "Created $id/date."

