#!/bin/sh

name="$1"

if [ ! "$name" ]; then
    echo 'garf dir: no directory name given.'
    exit 1
fi

case "$name" in
    src|source)
        echo "$HOME/pics/garfield" ;;
    posts)
        echo "$HOME/pics/eo/posts" ;;
    find)
        echo "$HOME/pics/eo/find" ;;
    unedited)
        echo "$HOME/pics/eo/unedited-test" ;;
    sundays)
        echo "$HOME/pics/eo/sundays" ;;
    old)
        echo "$HOME/pics/eo/old" ;;
    cache)
        echo "$HOME/.cache/garf" ;;

    *)
        echo "garf dir: unknown directory name '$name'"
        exit 1
        ;;
esac

