#!/bin/sh

alias type='xdotool type --clearmodifiers'
alias keys='xdotool key --clearmodifiers'

# Start file explorer
nohup thunar ~/pics > /dev/null 2>&1 &
# Wait for window to open
until xdotool search --onlyvisible --class 'thunar' > /dev/null; do
    sleep 0.1
done
sleep 0.1

# Navigate to directories
type eo
    keys Return
type posts
    keys Return End
    keys Ctrl+t BackSpace
type unedited
    keys Return Home

# Start file explorer
# nemo --tabs ~/pics/eo/posts ~/pics/eo/unedited >/dev/null 2>&1 &

# Change window mode
# i3-msg 'layout tabbed' > /dev/null

