#!/bin/sh

type() {
    xdotool type --clearmodifiers "$@"
}
keys() {
    xdotool key --clearmodifiers "$@"
}

# Start file explorer
nohup thunar ~/pics > /dev/null 2>&1 &
# Wait for window to open
until xdotool search --onlyvisible --class 'thunar' > /dev/null; do
    sleep 0.1
done

# Navigate to directories
type eo
    keys Return
type posts
    keys Return End
    keys Ctrl+t BackSpace
type unedited
    keys Return Home

# Change window mode
i3-msg 'layout tabbed' > /dev/null

