#!/bin/sh

posts="$(~/scripts/cmd/garf +dir 'posts' || exit 1)"
cd "$posts" || exit 1

for i in *; do
    if [ -f "$i/errata" ]; then
        echo "$i"
        cat "$i/errata"
        break
    fi
done

