#!/bin/sh

input="$1"
output="$2"
twothirds="$3"
if [ "$#" -lt 3 ]; then
    echo 'garf format: not enough arguments'
    exit 1
fi

watermarks="\
GarfEO
@garfield.eo
Garfield-EO
garfeo
Garfeo
Garfield Esperanto
garf-eo"

watermark="$(echo "$watermarks" | shuf -n1)"
comic-format "$input" "$output" "$text" --twothirds-adjust "$twothirds" >> /dev/null

