#!/bin/sh

dir="$HOME/pics/garfeo"

date="$1"
name="$2" # Optional

if [ ! "$date" ]; then
    echo 'garf make: date not given'
    exit 1
fi

input="$HOME/pics/garfield/$date.png"

if [ ! -f "$input" ]; then
    echo 'garf make: not the date of a real comic'
    exit 1
fi

# Make folder if does not exist
if [ ! -d "$dir/unedited" ]; then
    mkdir -p "$dir/unedited"
fi

# Check if folder already exists ending in same date
#   or has date file with same date
for folder in "$dir/unedited/"*; do
    if [ "$(expr "$folder" : '.*_\(.*\)')" = "$date" ] \
        || { [ -f "$folder/date" ] && [ "$(cat "$folder/date")" = "$date" ] ;} \
    ; then
        echo 'garf make: comic has already been formatted with that date'
        exit 1
    fi
done

# Convert image to square format, with watermark
~/scripts/cmd/garf +format "$input" "$dir/unedited/$date.png" || exit 1

# Create unique name for folder, if not specified as argument
if [ ! "$name" ]; then
    now=$(date +'%m%d%H')
    id=$(tr -dc '[:lower:]' < /dev/urandom | head -c 4)
    name="${now}_${id}_$date"
fi

# Create other files from image
~/scripts/cmd/garf +organize "$dir/unedited/$date.png" "$dir/unedited/$name" || exit 1
echo "Created $name"

