#!/bin/sh

src="$(     ~/scripts/cmd/garf +dir 'src')"      || { code="$?"; echo "$src";      exit "$code"; }
unedited="$(~/scripts/cmd/garf +dir 'unedited')" || { code="$?"; echo "$unedited"; exit "$code"; }
posts="$(   ~/scripts/cmd/garf +dir 'posts')"    || { code="$?"; echo "$posts";    exit "$code"; }

date=''
twothirds='' # --twothirds-adjust for comic-format
name=''      # Custom directory name
skip=0       # Skip existing post check

while true; do
    arg="$1"
    [ -n "$arg" ] || break
    shift

    case "$arg" in
        -r|--recent)
            if [ -n "$date" ]; then
                echo 'garf make: cannot specify date twice'
                exit 1
            fi
            date="$(~/scripts/cmd/garf +recent || exit 1)"
            if [ -z "$date" ]; then
                echo 'garf make: no recent comic'
                exit 1
            fi
            ;;

        -t|--twothirds)
            value="$1"
            if [ -z "$value" ]; then
                echo "garf make: missing value for $arg"
                exit 1
            fi
            shift
            if [ -n "$twothirds" ]; then
                echo 'garf make: cannot specify twothirds twice'
                exit 1
            fi
            twothirds="$value"
            ;;

        -n|--name)
            value="$1"
            if [ -z "$value" ]; then
                echo "garf make: missing value for $arg"
                exit 1
            fi
            shift
            if [ -n "$name" ]; then
                echo 'garf make: cannot specify name twice'
                exit 1
            fi
            name="$value"
            ;;

        -s|--skip)
            if [ "$skip" = 1 ]; then
                echo 'garf make: cannot specify skip twice'
                exit 1
            fi
            skip=1
            ;;

        -*)
            echo "garf make: invalid option $arg"
            exit 1
            ;;


        *)
            if [ -n "$date" ]; then
                echo 'garf make: cannot specify date twice'
                exit 1
            fi
            date="$arg"
            ;;
    esac
done

if [ -z "$date" ]; then
    echo 'garf make: date not given'
    exit 1
fi
date="$(basename "$date" .png)"
if ! date -d "$date" >/dev/null 2>&1; then
    echo "garf make: invalid date '$date'"
    exit 1
fi

if [ -z "$twothirds" ]; then
    twothirds='0'
fi

# Create unique name for folder, if not specified as argument
if [ -z "$name" ]; then
    if date -d "$date" +'%A' | grep -q 'Sunday';
        then case='upper'
        else case='lower'
    fi
    id=$(tr -dc "[:$case:]" < /dev/urandom | head -c 4)
    name="$id:$date"
fi

# Use filename if date is image path
date=$(basename "$date" .png)

input="$src/$date.png"
if [ ! -f "$input" ]; then
    echo 'garf make: not the date of a real comic'
    exit 1
fi

# Make folder if does not exist
if [ ! -d "$unedited" ]; then
    mkdir -p "$unedited"
fi

# Check if folder already exists ending in same date
#   or has date file with same date
for file in "$unedited/"*'/date'; do
    if [ "$(cat "$file")" = "$date" ]; then
        echo 'garf make: comic has already been formatted with that date'
        exit 1
    fi
done
if [ "$skip" = 0 ]; then
    for file in "$posts/"*'/date'; do
        if [ "$(cat "$file")" = "$date" ]; then
            echo 'garf make: comic has already been translated with that date'
            exit 1
        fi
    done
fi

# Convert image to square format, with watermark
~/scripts/cmd/garf +format "$input" "$unedited/$date.png" "$twothirds" || exit 1

# Create other files from image
~/scripts/cmd/garf +organize "$unedited/$date.png" "$unedited/$name" || exit 1
echo "Created $name"

