#!/bin/sh

posts="$(~/scripts/cmd/garf +dir 'posts')" || { code="$?"; echo "$posts"; exit "$code"; }
old="$(  ~/scripts/cmd/garf +dir 'old')"   || { code="$?"; echo "$old";   exit "$code"; }

id="$1"

if [ ! "$id" ]; then
    echo 'garf old: no post id given'
    exit 1
fi
if [ ! -d "$posts/$id" ]; then
    echo 'garf revise: no post with that id'
    exit 1
fi

number=0
for folder in "$old/$id:"*; do
    if [ -d "$folder" ]; then
        prev="$(echo "$folder" | sed "s|^$old/$id:||")"
        if [ "$prev" -ge "$number" ]; then
            number=$((prev + 1))
        fi
    fi
done

mv "$posts/$id" "$old/$id:$number" || exit 1
echo "Moved $id to old folder as version :$number"

