#!/bin/sh

old="$(~/scripts/cmd/garf +dir 'old' || exit 1)"

id="$1"
if [ ! "$id" ]; then
    echo 'garf old: no post id given'
    exit 1
fi

number=0
for folder in "$old/$id:"*; do
    if [ -d "$folder" ]; then
        prev="$(echo "$folder" | sed "s|^$old/$id:||")"
        if [ "$prev" -ge "$number" ]; then
            number=$((prev + 1))
        fi
    fi
done

echo "$old/$id:$number"

