#!/bin/sh

cache_file="$(~/scripts/cmd/garf +dir 'cache')" || { code="$?"; echo "$cache_file"; exit "$code"; }

count="$1"
[ "$count" ] || count='1'

[ -f "$cache_file" ] && tail -n "$count" "$cache_file"

