#!/bin/sh

posts="$(   ~/scripts/cmd/garf +dir 'posts'    || exit 1)"
unedited="$(~/scripts/cmd/garf +dir 'unedited' || exit 1)"

cd "$posts" || exit 1

post="$1"

if [ ! "$post" ]; then
    # Get first post id with no SVG file
    if [ ! "$post" ]; then
        for i in *; do
            if [ ! -f "$i/esperanto.svg" ]; then
                post="$i"
                break
            fi
        done
    fi

    # No post to revise!
    if [ ! "$post" ]; then
        echo 'garf revise: no post missing SVG file'
        exit 0
    fi

    echo "Post id: $post"
fi

# Invalid post id
if [ ! -d "$post" ]; then
    echo 'garf revise: no post with that id'
    exit 1
fi

# Find date if not existing file
if [ ! -f "$post/date" ]; then
    echo 'No date file, please find from post'
    ~/scripts/cmd/garf date "$post" || exit "$?"
fi

# Read date file (existing or just created)
date="$(cat "$post/date")"
echo "Date: $date"

# Make post
~/scripts/cmd/garf make "$date" '0' "$post" || exit "$?"

# Copy other files
cp "$post/title"  "$unedited/$post/title" || exit 1
if [ -f "$post/props" ]; then
    cp "$post/props"  "$unedited/$post/props" || exit 1
fi
if [ -f "$post/transcript" ]; then
    cp "$post/transcript"  "$unedited/$post/transcript.old" || exit 1
fi
if [ -f "$post/special" ]; then
    cp "$post/special"  "$unedited/$post/special" || exit 1
fi

# Move old post to old
printf 'Move old post to old folder? '
read -r
~/scripts/cmd/garf +old "$post" || exit "$?"

# Wait until edited
echo '(waiting until done...)'
until [ -d "$post" ]; do
    sleep 0.5
done

# Transcribe
printf 'Transcribe now? '
read -r
~/scripts/cmd/garf transcribe "$post" || exit "$?"

