#!/bin/sh

dir=~/scripts/garf

# Missing command
if [ ! "$1" ]; then
    echo 'garf: missing subcommand'
    echo "    available subcommands: [help|show|make|find]"
    exit 1
fi

# Remove subcommand from $@
cmd="$1"
shift

case "$cmd" in
    # Help
    'help'|'h'|'--help'|'-h')
        echo 'garf: available subcommands'
        echo '    show: display a comic'
        echo '    make: make post data including formatted comic'
        echo '    find: open all comics with given month and day, or post id'
        exit 0
        ;;

    # Public
    'show'|'s')
        $dir/show $@
        ;;
    'make'|'m')
        $dir/make $@
        ;;
    'find'|'f')
        $dir/find $@
        ;;

    # 'add-date'|'fp')
    #     $dir/add-date $@
    #     ;;

    # Private
    '+format')
        $dir/format $@
        ;;
    '+organize')
        $dir/organize $@
        ;;

    *)
        echo "garf: unknown subcommand: '$cmd'"
        echo "    available subcommands: [help|show|make|find]"
        exit 1
        ;;
esac

