#!/bin/sh

src="$(~/scripts/cmd/garf +dir 'src' || exit 1)"

date="$1"

# Handle argument options
while getopts 'rh' opt; do
    case "$opt" in

    # Replace prevous instance of `display`
    r)
        if pgrep display; then
            killall display > /dev/null
        fi
        # Set date to next argument, after switch
        date="$2"
        ;;

    # Help
    *)
        echo 'garf show'
        echo '    -r  replace previous displayed image'
        echo '    [DATE] (default: random date)'
        exit 0
        ;;

esac
done

if [ "$date" ]; then
    # Date given as argument
    file="$src/$date.png"
else
    # Get 1 random file in directory
    file=$(find "$src" | shuf -n 1)
fi

# File not found
if [ ! -f "$file" ]; then
    echo 'garf show: not the date of a real comic'
    exit 1
fi

echo "$file"
display "$file"

