#!/bin/sh

src="$(~/scripts/cmd/garf +dir 'src' || exit 1)"
cache_file="$HOME/.cache/garf"

date="$1"

# Handle argument options
while getopts 'rh' opt; do
    case "$opt" in

    # Replace prevous instance of `display`
    r)
        pkill -f -c 'garf-show'
        # Set date to next argument, after switch
        date="$2"
        ;;

    # Help
    *)
        echo 'garf show'
        echo '    -r  replace previous displayed image'
        echo '    [DATE] (default: random date)'
        exit 0
        ;;

esac
done

if [ "$date" ]; then
    # Date given as argument
    file="$src/$date.png"
else
    # Get 1 random file in directory
    file=$(find "$src" | shuf -n 1)
fi

# File not found
if [ ! -f "$file" ]; then
    echo 'garf show: not the date of a real comic'
    exit 1
fi

echo "$file"
echo "$file" >> "$cache_file"

# feh "$file" --fullscreen --auto-zoom --class 'garf-show'
nsxiv "$file" --fullscreen --scale-mode f --class 'garf-show'

