#!/bin/sh

src="$(       ~/scripts/cmd/garf +dir 'src')"   || { code="$?"; echo "$src";        exit "$code"; }
cache_file="$(~/scripts/cmd/garf +dir 'cache')" || { code="$?"; echo "$cache_file"; exit "$code"; }

date="$1"

# Handle argument options
while getopts 'rh' opt; do
    case "$opt" in

    # Help
    *)
        echo 'garf show'
        echo '    -r  replace previous displayed image'
        echo '    [DATE] (default: random date)'
        exit 0
        ;;

esac
done

if [ "$date" ]; then
    # Date given as argument
    file="$src/$date.png"
else
    # Get 1 random file in directory
    file=$(find "$src" | shuf -n 1)
fi

# File not found
if [ ! -f "$file" ]; then
    echo 'garf show: not the date of a real comic'
    exit 1
fi

echo "$file"
echo "$file" >> "$cache_file"

pkill -f -c 'garf-show'

# feh "$file" --fullscreen --auto-zoom --class 'garf-show'
nsxiv "$file" --fullscreen --scale-mode f --class 'garf-show'

