#!/bin/sh

posts="$(~/scripts/cmd/garf +dir 'posts')" || { code="$?"; echo "$posts"; exit "$code"; }

cd "$posts" || exit 1

total=0
editable=0
transcribed=0

for i in *; do
    total=$((total + 1))
    [ -f "$i/esperanto.svg" ] && editable=$((editable + 1))
    [ -f "$i/transcript" ] && transcribed=$((transcribed + 1))
done

print() {
    name="$1"
    value="$2"
    percent=$(((value * 100) / total))
    printf '\033[3m%s \033[0;1m%3s\033[0;2m / \033[0m%3d \033[2m= \033[0;1m%2d\033[2m%%\033[0m\n' "$name" "$value" "$total" "$percent"
}

print 'Editable:   ' "$editable"
print 'Transcribed:' "$transcribed"

percent=$((((editable + transcribed) * 100) / 2 / total))
printf 'Total: \033[1m%2d\033[2m%%\033[0m\n' "$percent"

