#!/bin/sh

src="$(~/scripts/cmd/garf +dir 'src'     || exit 1)"
out="$(~/scripts/cmd/garf +dir 'sundays' || exit 1)"

# Create out folder if it does not exist
if [ ! -d "$out" ]; then
    mkdir "$out"
fi

# Remove previous files in folder
if [ "$(ls -A "$out")" ]; then
    rm "$out/"*
fi

count=1
for file in "$src"/*; do
    if [ $((count % 7)) -eq 0 ]; then
        cp "$file" "$out/"
    fi
    count=$((count + 1))
done

# Open dolphin and ignore stdout/stderr
nohup dolphin "$out" >> /dev/null 2>&1

