#!/bin/sh

posts="$(~/scripts/cmd/garf +dir 'posts'    || exit 1)"

cd "$posts" || exit 1

post="$1"

if [ ! "$post" ]; then
    # Get first NOT-OLD post id with no transcript file
    for i in *; do
        if [ -f "$i/esperanto.svg" ] && [ ! -f "$i/transcript" ]; then
            post="$i"
            break
        fi
    done

    if [ -z "$post" ]; then
        # Get first post id with no transcript file
        for i in *; do
            if [ ! -f "$i/transcript" ]; then
                post="$i"
                break
            fi
        done

        # No post to transcribe!
        if [ -z "$post" ]; then
            echo 'garf transcribe: no posts with missing trascript file'
            exit 0
        fi
    fi

    echo "Post id: $post"
fi

# Invalid post id
if [ ! -d "$post" ]; then
    echo 'garf transcript: no post with that id'
    exit 1
fi

cd "$post" || exit 1

temp_file="/tmp/garf-transcript-$post"

# Template file contents: 3 panels or 7 for Sundays
number="$(echo "$post" | sed 's/^0*//')"
[ "$(((number + 1) % 7))" -eq 0 ] \
    || file_contents="$(printf -- '---\n---\n---\n---\n---\n---')" \
    && file_contents="$(printf -- '---\n---')"

# Show image, kill previous instance
pkill -f -c 'garf-transcribe' > /dev/null
nsxiv 'esperanto.png' 'english.png' --class 'garf-transcribe' &

# Move image window, based on monitor count
sleep 0.1
[ "$(~/scripts/cmd/monitors)" = 1 ] \
    || i3_cmd='move to output HDMI-1' \
    && i3_cmd='move right, resize set 40 ppt'
i3-msg "[instance=garf-transcribe] $i3_cmd, focus left" > /dev/null

# Open file
echo "$file_contents" > "$temp_file"
nvim "$temp_file"

# Kill image
pkill -f -c 'garf-transcribe' > /dev/null

# Confirm, if file changed, and not interrupted
if [ "$(cat "$temp_file")" = "$file_contents" ]; then
    echo 'No changes made.'
    exit 0
fi
printf 'Save transcript file? (CTRL-C to cancel) '
read -r

mv "$temp_file" 'transcript'
echo 'Saved transcript file.'

