#!/bin/sh

# Help
if [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    echo 'denote: Format note file, removing junk, and save as plaintext'
    echo '  Usage: denote [FILE]'
    echo '    Saves to [FILE].txt'
    echo '  Usage: denote [FILE] -p'
    echo '    Prints to stdout'
    exit 0
fi

# No filename argument
if [ ! "$1" ]; then
  echo 'denote: missing file'
  echo '  Use --help for information'
  exit 1
fi

# Remove duplicate newlines (more than 2 in a row)
# Remove lines beginning with space
# Combine lines separated by single newline (less than 2 in a row)
# Wrap words to fit width
out=$(cat $1 -s \
    | sed '/^ /d' \
    | awk 'BEGIN{ RS="\n\n"; ORS="\n\n" } { gsub("\n"," "); print }' \
    | sed 's/ +/ /g' \
    | fmt -w 80)

# Print to sdout or save to file
if [ "$2" = '-p' ] || [ "$2" = '--print' ]; then
    echo "$out"
else
    name="$1.txt"
    echo "$out" > "$name" && echo "Saved output to '$name'"
fi

