#!/bin/sh

date="$1"

# Handle argument options
while getopts 'rh' opt; do
    case "$opt" in

    # Replace prevous instance of `display`
    r)
        if pgrep display; then
            killall display > /dev/null
            echo "Replaced previous displayed image"
        fi
        # Set date to next argument, after switch
        date="$2"
        ;;

    # Help
    *)
        echo "Garfield comic"
        echo "    -r  Replace previous displayed image"
        echo "    [DATE] (default: random date)"
        exit 0
        ;;

esac
done

# Directory of comics
dir=~/pics/garfield

if [ "$date" ]; then
    # Date given as argument
    file="$dir/$date.png"
else
    # Get 1 random file in directory
    file=$(find "$dir" | shuf -n 1)
fi

echo "$file"
display "$file"

