#!/bin/sh

# Handle argument options
while getopts 'rh' opt; do
  case "$opt" in
    
    # Replace prevous instance of `display`
    r)
      killall display &> /dev/null
      echo "Replaced previous displayed image"
      ;;

    # Help
    ?|h)
      echo "Garfield comic"
      echo "    -r  Replace previous displayed image"
      echo "    [DATE] (default: random date)"
      exit 1
      ;;

  esac
done

# Set $1 to next argument
shift "$(($OPTIND -1))"

# Directory of comics
dir=~/pics/garfield

if [ $1 ]; then
  # Date given as argument
  file=$dir/$1.png
else
  # Get 1 random file in directory
  file=$( find $dir | shuf -n 1 )
fi

echo $file
display $file 

