#!/bin/sh

date="$1"
name="$2" # Optional

if [ ! "$date" ]; then
    echo 'date not given'
    exit 1
fi

input="$HOME/pics/garfield/$date.png"

if [ ! -f "$input" ]; then
    echo 'not the date of a real comic'
    exit 1
fi

cd "$HOME/pics/garfeo" || exit 1

# Make folder if does not exist
if [ ! -d "unedited" ]; then
    mkdir -p "unedited"
fi

# Check if folder already exists with same date
for folder in 'unedited/'*; do
    if [ "$(expr "$folder" : '.*_\(.*\)')" = "$date" ]; then
        echo 'comic has already been formatted with that date'
        exit 1
    fi
done

# Convert image to square format, with watermark
garf-convert "$input" "unedited/$date.png" >> /dev/null

# Create unique name for folder, if not specified as argument
if [ ! "$name" ]; then
    now=$(date +'%m%d%H')
    id=$(tr -dc 'a-z' < /dev/urandom | head -c 4)
    name="${now}_${id}_$date"
fi

# Create other files from image
garf-organize "unedited/$date.png" "unedited/$name"
echo "Created $name"

