#!/bin/sh

img="$1"
if [ ! "$img" ]; then
    echo 'image path not given'
    exit 1
fi

dir="$2"
if [ ! "$dir" ]; then
    echo 'directory not exist'
    exit 1
fi

mkdir "$dir"

cp "$img" "$dir/english.png"
cp "$img" "$dir/esperanto.png"
touch "$dir/title"

date=$(basename "$img" .png)
echo "$date" > "$dir/date"

trash "$img"

