#!/bin/sh

if [ ! "$1" ]; then
    echo 'mkscript: no filename given.'
    exit 1
fi

if [ -e "$1" ]; then
    echo "mkscript: file or directory already exists named '$1'"
    exit 1
fi

# Create file
echo -e '#!/bin/sh\n\n' > "$1"
# Set as executable
chmod +x "$1"

