#!/bin/sh

# Directory to download to
location="$HOME/music/CoolSongs"
# Link to playlist to download
playlist='https://open.spotify.com/playlist/6mczz83X2b8KZSYyp3vWFr?si=5dc50a06f2014f4e'
# Filename of track
trackname='{list-position} {title} - {artists}'

# Remove old folder
trash $location
# Create new folder
mkdir $location
cd $location
# Downloads songs to folder, with formatted filename
spotdl $playlist --output "$trackname"

