#!/bin/sh

folder='~/Music/CoolSongs'
link='https://open.spotify.com/playlist/6mczz83X2b8KZSYyp3vWFr?si=5dc50a06f2014f4e'
filename='{list-position} {title} - {artists}'

# Rename old folder
mv -r $folder $folder.old
# Create new folder
mkdir $folder
cd $folder
# Downloads songs to folder, with formatted filename
spotdl $link --output $filename
# Remove old folder
# trash $folder.old

