#!/bin/sh

# Directory to download to
location="$HOME/music/CoolSongs"
# Link to playlist to download
playlist='https://open.spotify.com/playlist/6mczz83X2b8KZSYyp3vWFr?si=5dc50a06f2014f4e'
# Filename of track
trackname='{list-position} {title} - {artists}'

# Confirm
echo 'Remove and redownload all songs'
printf 'Are you sure? [Y/n] '

# Return if input was not 'Y' or blank (enter key)
read -r confirm
case "$confirm" in
    y|Y|"") ;;
    *)
        echo 'Cancelled.'
        exit 0
        ;;
esac

# Remove old folder
if [ -d "$location" ]; then
    trash "$location"
fi
# Create new folder
mkdir -p "$location"
cd "$location" || exit 1
# Downloads songs to folder, with formatted filename
spotdl "$playlist" --output "$trackname" || exit 1
notify-send 'Spotify download complete.'

