#!/bin/sh

echo 'Remove and redownload all songs'
read -p 'Are you sure? ' -n 1 -r

if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo
  echo 'Starting spotdl...'

  cd ~/Music/CoolSongs/
  rm -f *
  spotdl --output '{list-position} {title} - {artist}' 'https://open.spotify.com/playlist/6mczz83X2b8KZSYyp3vWFr?si=3c002230a0ef4eb2'
fi

