#!/bin/sh

# Handle arguments
while getopts 'kdh' opt; do
  case "$opt" in

    k) do_kill=true ;;
    d) do_daemon=true ;;

    # Help
    h)
      echo "Spotify"
      echo "    -k  Kill daemon, if running"
      echo "    -d  Start new daemon, if not running"
      exit 1
      ;;

  esac
done

# Kill existing daemon
if [ $do_kill ]; then
  if pgrep "spotifyd" &> /dev/null; then
    killall spotifyd
    echo "  info: Killed existing daemon"
  else
    echo "  info: No daemon running"
  fi
fi

# Start new daemon
if [ $do_daemon ]; then
  if ! pgrep "spotifyd" &> /dev/null; then
    spotifyd
    echo "  info: Started new daemon"
  else
    echo "  info: Daemon already running"
  fi
fi

# Open client
echo "Starting spotify client"
/bin/spt || echo "Failed to open spotify! Maybe no internet?"
