#!/bin/sh
export INFO='add metadata to an audio file'

for file in "$@"; do
    echo '-------------'
    echo "$file"

    printf 'Title:  '; read -r title
    printf 'Artist: '; read -r artist
    printf 'Album:  '; read -r album

    image="${file%.*}.jpg"

    temp='.temp.mp3'
    mv "$file" "$temp"

    lame "$temp" "$file" \
        --tt "$title" \
        --ta "$artist" \
        --tl "$album" \
        --ti "$image"

    trash "$temp"
done

