#!/bin/sh

# Require arguments
if [ ! "$1" ]; then
    echo "max count not specified"
    exit 1
fi
if [ ! "$2" ]; then
    echo "starting index not specified"
    exit 1
fi

# Get links, separated by linebreaks
links=$(\
    cut -d ',' -f 2 subscriptions.csv \
    | tail -n +2 \
    | tail -n "+$2" \
    | head -n "$1" \
)

# Open every link
for i in $links; do
    echo $i
    $BROWSER $i
done


