#!/bin/sh
export INFO='toggle or restart picom compositor'

start() {
    # --transparent-cliping : don't render windows below, in tabbed/stacked view
    # picom --transparent-clipping --backend glx &
    picom --backend glx &
}

stop() {
    killall picom
}

case "$1" in

    # Kill and restart, to fix rendering issues
    'restart')
        stop
        while pgrep -x picom; do true; done
        start
        ;;

    'toggle')
        if pgrep -x picom;
            then stop
            else start
        fi
        ;;

    *)
        echo 'picom-exec: invalid subcommand'
        exit 1
        ;;
esac


