#!/bin/sh

name='^Minecraft '
timeout=1

wid="$(xdotool search --name "$name" | head -n1)"
if [ -z "$wid" ]; then
    echo 'No window found.'
    exit 1
fi

echo "Running autoclicker..."
echo "Window ID: $wid"

trap stop INT
stop() {
    # Raise right click
    xdotool mouseup --window "$wid" 3
    echo
    echo 'Stopped.'
    exit 0
}

while sleep "$timeout"; do
    # Hold down right click
    xdotool mousedown --window "$wid" 3
    # Short left click
    xdotool click --window "$wid" 1

    # Reset screensaver timeout
    xset s reset
done

