#!/bin/sh

name='^Minecraft '
timeout=1

# Must be single instance
for pid in $(pgrep "$(basename $0)"); do
    if [ ! "$pid" = "$$" ]; then
        kill "$pid" -INT
        echo 'Killed previous instance.'
    fi
done

wid="$(xdotool search --name "$name" | head -n1)"
if [ -z "$wid" ]; then
    echo 'No window found.'
    exit 1
fi

echo "Running autoclicker..."
echo "Window ID: $wid"

trap stop INT
stop() {
    # Raise right click
    xdotool mouseup --window "$wid" 3
    # Re-enable screensaver
    # xset s on
    xdg-screensaver resume "$wid"

    echo
    echo 'Stopped.'
    exit 0
}

# Disable screensaver
# xset s off
# xset s noblank
xdg-screensaver suspend "$wid"

while sleep "$timeout"; do
    # Hold down right click
    xdotool mousedown --window "$wid" 3
    # Short left click
    xdotool click --window "$wid" 1
done

