#!/bin/sh
export INFO='quickly backup a directory locally'

location='.backups'

if [ -z "$1" ]; then
    echo "backup-file: missing argument." >&2
    exit 1
fi

files="$*"
if [ "$#" -eq 1 ] && [ "$1" = '.' ]; then
    files="$(basename "$PWD")"
    is_cwd=1
    cd ..
fi

if [ ! -e "$location" ]; then
    mkdir -p "$location"
elif [ ! -d "$location" ]; then
    echo "backup-dir: $location exists and is not a directory." >&2
    exit 1
fi

timecode="$(date '+%Y-%m-%d-%H%M')"
dir="$location/$timecode"

if [ ! -e "$dir" ]; then
    mkdir -p "$dir"
elif [ ! -d "$dir" ]; then
    echo "backup-dir: $dir exists and is not a directory." >&2
    exit 2
fi

for file in $files; do
    rsync --archive --exclude="$location" "$file" "$dir/$file" || exit 2

    [ -n "$is_cwd" ] && printf '../'
    echo "$dir/$file"
done

