#!/bin/sh
export INFO='quickly backup a directory locally'

location='.backups'

dir="$1"
if [ -z "$dir" ]; then
    echo "backup-dir: missing argument."
    exit 1
elif [ ! -d "$dir" ]; then
    echo "backup-dir: argument $dir is not a directory."
    exit 1
fi

if [ ! -e "$location" ]; then
    mkdir -p "$location"
elif [ ! -d "$location" ]; then
    echo "backup-dir: $location exists and is not a directory."
    exit 1
fi

id="$dir:$(date '+%Y-%m-%d-%H-%M-%S')"

cp -a "$dir" "$location/$id" || exit 2

echo "$location/$id"

