#!/bin/sh
export INFO='display battery percentage with an icon'

~/scripts/cmd/require acpi || exit $?

icon_battery=''
icon_plug=''
icon_lightning=''

if [ "$1" = '--color' ]; then
    color='%{F#FFDD22}'
    reset='%{F-}'
fi

info=$(acpi --battery | head -n1)

percent=$(echo "$info" | grep -o '[0-9]*%')
percent="${percent%\%}"

if echo "$info" | grep -q "Discharging";
    then icon="$icon_battery"
    else icon="$color$icon_lightning$reset $icon_plug"
fi

echo "$icon $color$percent%$reset"

