#!/bin/sh
export INFO='shuffle backgrounds every so often'

dir="$HOME/pics/wallpapers"
delay=300 # 5 minutes

change() {
    feh --randomize --bg-scale "$dir/"*
}

if [ "$1" = '--forever' ]; then
    while true; do
        change
        sleep "$delay"
    done
else
    change
fi

