#!/bin/sh
export INFO='shuffle backgrounds every so often'

dir="$HOME/.config/wallpapers"

delay="$1"

change() {
    feh --randomize --bg-scale "$dir/"*
}

# Just change once
if [ -z "$delay" ]; then
    change
    exit 0
fi

# Kill running instances
for pid in $(pgrep -f "$(basename "$0")"); do
    [ "$pid" != "$$" ] || kill "$pid"
done

# Loop forever
while true; do
    change
    sleep "$delay"
done

