#!/bin/sh
#~~~ connect or disconnect a particular bluetooth device

mac='40:DE:17:43:2F:49'

# Start scanning for all devices, until given MAC address is found
scan_and_wait() {
    bluetoothctl scan on &
    while ! bluetoothctl devices | grep -q "$mac"; do
        sleep 1
    done
    bluetoothctl scan off
}

# Run subcommand
case "$1" in
    connect)
        bluetoothctl power on
        scan_and_wait
        bluetoothctl connect $mac
        # Lower volume, because it keeps resetting to 100%
        sleep 1
        pactl set-sink-volume @DEFAULT_SINK@ 40%
        ;;

    disconnect)
        bluetoothctl disconnect $mac
        bluetoothctl power off
        ;;

    mac) echo $mac ;;

    status) bluetoothctl devices | grep -q "$mac" ;;

    *)
        echo 'bt: please provide valid subcommand'
        echo 'usage: [ connect | disconnect | mac | status ]'
        ;;
esac

