#!/bin/sh
#~~~ connect or disconnect a particular bluetooth device

mac='40:DE:17:43:2F:49'

# Start scanning for all devices, until given MAC address is found
scan_and_wait() {
    bluetoothctl scan on &
    while ! bluetoothctl devices | grep -q "$mac"; do
        sleep 1
    done
    bluetoothctl scan off
    killall bluetoothctl
}

# Run subcommand
case "$1" in
    'connect')
        pactl set-sink-volume @DEFAULT_SINK@ 0%
        bluetoothctl power on
        scan_and_wait
        bluetoothctl connect $mac
        ;;

    'disconnect')
        bluetoothctl disconnect $mac
        bluetoothctl power off
        # Mute audio when bluetooth disconnected
        sleep 1
        pactl set-sink-volume @DEFAULT_SINK@ 0%
        ;;

    'mac') echo $mac ;;

    'status') bluetoothctl devices | grep -q "$mac" ;;

    *)
        echo 'bt: please provide valid subcommand'
        echo 'usage: [ connect | disconnect | mac | status ]'
        ;;
esac

