#!/bin/sh
export INFO='print a nice rainbow color pattern'

bg=-1
while [ "$bg" -le 7 ]; do
    offset=0
    while [ "$offset" -le 1 ]; do
        fg=0
        while [ "$fg" -le 7 ]; do
            if [ "$bg" -lt 0 ]; then
                printf '\033[0m'
            else
                printf '\033[48;5;%sm' "$((bg + offset * 8))"
            fi
            printf '\033[38;5;%sm' "$((fg + offset * 8))"
            printf '* '
            printf '\033[0m'
            fg=$((fg + 1))
        done
        offset=$((offset + 1))
        printf '  '
    done
    bg=$((bg + 1))
    echo
done

echo
offset=0
while [ "$offset" -le 1 ]; do
    bg=0
    while [ "$bg" -le 7 ]; do
        printf '\033[48;5;%sm' "$((bg + offset * 8))"
        printf '   '
        printf '\033[0m'

        bg=$((bg + 1))
    done
    offset=$((offset + 1))
    echo
done

echo
printf 'Normal    \033[1mBold\n'
printf '\033[0;3mItalic \033[1mBoldItalic\n'

