#!/bin/sh
export INFO='enable or disable battery conservation with tlp'

~/scripts/cmd/require tlp gksu notify-send rofi sudo

battery='BAT0'
driver='/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00'

get_status() {
    [ "$(cat "$driver/conservation_mode" || exit $?)" = '1' ]
}

case "$1" in
    'off') sudo tlp setcharge 0 0 "$battery" ;;
    'on')  sudo tlp setcharge 1 1 "$battery" ;;

    'status') get_status ;;

    'gui')
        if get_status; then
            state='Enabled'
        else
            state='Disabled'
        fi

        title='Conservation mode'
        option_enable='Enable - for AC power'
        option_disable='Disable - for battery'

        # Sort options, inactive first
        # Perhaps this is should always be same order
        if [ "$state" = 'Enabled' ]; then
            option_1="$option_disable"
            option_2="$option_enable"
        else
            option_1="$option_enable"
            option_2="$option_disable"
        fi

        answer="$(
            printf '%s\n%s' "$option_1" "$option_2" \
            | rofi -dmenu -i \
                -p "$title" \
                -mesg "Currently $state"
        )"

        case "$answer" in
            'Disable'*)
                gksu tlp setcharge 0 0 "$battery" \
                    || notify-send -t 3000 -a "$title" 'Failed to disable conservation mode' \
                    && notify-send -t 1500 -a "$title" 'Conservation mode DISABLED'
                ;;
            'Enable'*)
                gksu tlp setcharge 1 1 "$battery" \
                    || notify-send -t 3000 -a "$title" 'Failed to enable conservation mode' \
                    && notify-send -t 1500 -a "$title" 'Conservation mode ENABLED'
                ;;
            *)
                echo 'Cancelled'
                exit 0
                ;;
        esac
        ;;

    'h'|'help'|'-h'|'--help')
        echo 'Conservation mode'
        echo '    Usage:'
        echo '        conservation [SUBCOMMAND]'
        echo '    Subcommands:'
        echo '      - on     Enable'
        echo '      - off    Disable'
        echo '      - gui    Ask using rofi gui'
        echo '      - status Get current state (as exit code)'
        echo '      - help   Show this message'
        ;;

    *)
        echo 'conservation: please provide subcommand: [ on | off | gui | status | help ]'
        exit 1
        ;;
esac

