#!/bin/sh
#~~~ enable or disable battery conservation with tlp

case "$1" in
    'off')
        sudo tlp setcharge 0 0 BAT0 && echo 'Success'
        ;;

    'on')
        sudo tlp setcharge 1 1 BAT0 && echo 'Success'
        ;;

    'gui')
        if [ "$($0 status)" ]; then
            state='ENABLED'
        else
            state='DISABLED'
        fi
        ans="$( zenity --info \
            --text="Change conservation Mode\n(Currently $state)" \
            --ok-label 'Disable' \
            --extra-button 'Enable' \
            --title 'Conservation Mode'
        )"
        case "$?-$ans" in
            '0-')
                gksu tlp setcharge 0 0 BAT0 \
                    && notify-send -t 1500 -a 'Conservation Mode' 'Conservation mode DISABLED'
                ;;
            '1-Enable')
                gksu tlp setcharge 1 1 BAT0 \
                    && notify-send -t 1500 -a 'Conservation Mode' 'Conservation mode ENABLED'
                ;;
            *)
                exit
                ;;
        esac
        ;;

    'status')
        status="$(cat /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode || exit $?)"
        [ "$status" = '1' ]
        ;;

    h|help|-h|--help)
        echo 'Conservation mode'
        echo '    Usage:'
        echo '        consv [SUBCOMMAND]'
        echo '    Subcommands:'
        echo '      - on     Enable'
        echo '      - off    Disable'
        echo '      - gui    Ask using zenity gui'
        echo '      - status Get current state (as exit code)'
        echo '      - help   Show this message'
        ;;

    *)
        echo 'consv: please provide subcommand: [ on | off | gui | status | help ]'
        exit
        ;;
esac

