#!/bin/sh
export INFO='get CPU usage percent for a program'

CPU_COUNT=16

pname="$1"
[ "$1" ] || {
    echo 'cpu-percent: missing process name.'
    exit 1
}

pid=$(pgrep "$pname")
[ -n "$pid" ] || {
    echo "cpu-percent: $pname is not running."
    exit 1
}

cpu_usage=$(top -b -n 2 -d 0.2 -p "$pid" | tail -1 | awk '{print $9}')
cpu_usage=$((${cpu_usage%.*} / CPU_COUNT))
echo "$cpu_usage%"


