#!/bin/sh
#~~~ custom version of dmenu_run to use aliases

# Set aliases
# Priority before $path
alias lw='librewolf'
alias lo='libreoffice'
alias th='thunar'
alias ff='firefox'

# Set paths to look for executables
# Similar to $PATH, but more narrow
# Order is priority
path="
$HOME/scripts/cmd
$HOME/.cargo/bin
/usr/bin
/bin
"

# Path to cache executables
# Because looking for files in $path is SLOW
cache_file="$HOME/.cache/dmenu-custom"

# Create cache file if does not exist
# Or manual refresh is requested
if [ ! -f "$cache_file" ] || [ "$1" = 'refresh' ]; then
    echo "Updating cache..."

    # Add aliases to dmenu options
    cmds=""
    for alias in $(alias); do
        cmd="${alias%%=*}"
        cmds="$cmds$cmd "
    done

    # Add commands from $PATH
    for folder in $path; do
        if [ ! -d "$folder" ]; then
            continue
        fi
        for file in "$folder"/*; do
            if [ ! -x "$file" ]; then
                continue
            fi
            cmd=$(basename "$file") 
            cmds="$cmds$cmd "
        done
    done

    # Replace spaces with newlines
    # Remove duplicates
    cmds=$(echo "$cmds" | sed 's/ /\n/g' | awk '!seen[$0]++')
    # Write to cache file
    echo "$cmds" > "$cache_file"

    # Exit only if manual refresh was requsted
    # Not if creating cache automatically due to missing file
    if [ "$1" = 'refresh' ]; then
        exit
    fi
else
    # Just read cache file
    cmds=$(cat "$cache_file")
fi

# Use dmenu to ask which command to run
run=$(echo "$cmds" | dmenu -b)
# Eval is needed, to run aliases as well
eval "$run"
