#!/bin/sh
export INFO='open dmenu to find an emoji'

~/scripts/cmd/require rofi notify-send || exit $?

add_style='s/^\([^ ]*\)/<span size="13000">\1<\/span>/'
remove_style='s/^<[^>]*>\([^ <]*\).*$/\1/'

chosen=$(sed "$add_style" ~/scripts/share/emojis | rofi -dmenu -i -l 30 -markup-rows | sed "$remove_style")
[ -n "$chosen" ] || exit 0

echo "$chosen"

# Type chosen emoji, or copy to clipboard
# xdotool type "$chosen"
printf "%s" "$chosen" | xclip -selection clipboard
notify-send "$chosen" -t 800

