#!/bin/sh
export INFO='open dmenu to find an emoji'

~/scripts/cmd/require wofi notify-send || exit $?
# TODO: Use wayland-compatible clipboard

ADD_STYLE='s/^\([^ ]*\)/<span size="13000">\1<\/span>/'
REMOVE_STYLE='s/^<[^>]*>\([^ <]*\).*$/\1/'

chosen=$(sed "$ADD_STYLE" ~/scripts/share/emojis \
    | wofi --show dmenu \
        --allow-markup \
    | sed "$REMOVE_STYLE"
)
[ -n "$chosen" ] || exit 0

echo "$chosen"

# Type chosen emoji, or copy to clipboard
# xdotool type "$chosen"
printf "%s" "$chosen" | xclip -selection clipboard
notify-send "$chosen" -t 800

