#!/bin/sh
export INFO='choose an emoji using fzf'

~/scripts/cmd/require fzf notify-send || exit $?

answer="$(cat ~/scripts/share/emojis \
    | fzf \
        --highlight-line \
    | cat \
|| exit $?)"

if [ -z "$answer" ]; then
    exit 0
fi

emoji="$(echo $answer | sed 's/ .*//')"
echo "$emoji"

