#!/bin/sh
export INFO='run ffmpeg on all files in current directory, converting one filetype to another'

if [ ! "$1" ]; then
    echo "ffmpegall: no input filetype given"
    exit 1
fi
if [ ! "$2" ]; then
    echo "ffmpegall: no output filetype given"
    exit 1
fi

for file in *."$1"; do
    echo "$file"
    ffmpeg -i "$file" "${file%.*}.$2" -loglevel error || exit 1
    trash "$file"
done

