#!/bin/sh
export INFO='run ffmpeg on all files in current directory, converting one filetype to another'

in="$1"
out="$2"
shift 2
if [ ! "$in" ]; then
    echo "ffmpegall: no input filetype given"
    exit 1
fi
if [ ! "$out" ]; then
    echo "ffmpegall: no output filetype given"
    exit 1
fi

for old in $(find . -maxdepth 1 | grep ".*\\.$in"); do
    basename "$old"
    ffmpeg -i "$old" "${old%.*}.$out" -loglevel error "$@" || exit 1
    trash "$old" || exit 1
done

