#!/bin/sh
export INFO='search and run a desktop application using fzf'

~/scripts/cmd/require fzf || exit $?

dirs="/usr/share/applications/ $XDG_DATA_HOME/applications/"

list_names() {
    #shellcheck disable=SC2086
    grep \
        --dereference-recursive \
        --no-filename \
        --max-count 1 \
        "^Name=" \
        $dirs \
        | sed 's/^Name=//'
}

resolve_file() {
    target="$1"
    #shellcheck disable=SC2086
    grep \
        --dereference-recursive \
        --files-with-matches \
        --max-count 1 \
        "^Name=$target$" \
        $dirs
}

extract_key() {
    key="$1"
    cat | grep --max-count 1 "^$key=" | sed "s/^$key=//"
}

answer="$(list_names \
    | fzf \
        --highlight-line \
    || exit $?)"

file="$(resolve_file "$answer")"
if [ -z "$file" ]; then
    exit 1
fi

cmd="$(extract_key 'Exec' < "$file"\
    | sed 's/%[^%]//g' \
    | sed "s/^\s*[\"']//;s/[\"']\s*$//" \
|| exit $?)"
if [ -z "$cmd" ]; then
    exit 2
fi

echo "$cmd"

