#!/bin/sh
export INFO='choose a directory using fzf'
# NOTE: Does NOT return >0 if `fzf` is cancelled! Instead check stdout!=""

if [ $# -ne 2 ]; then
    echo 'fzf-dir: incorrect usage.' >&2
    exit 1
fi

depth="$1"
dir="$2"

if [ -z "$dir" ]; then
    echo 'fzf-dir: missing directory.' >&2
    exit 1
fi

get_paths() {
    # Print mtime to sort, then remove
    find -L \
            "$dir" \
            -mindepth "$depth" -maxdepth "$depth" \
            -not -path '.*' \
            -printf '%T@ %p\n' \
        | sort -r \
        | awk '{print $2}'
}

trim_path() {
    cat | rev \
        | cut -d/ -f-"$depth" \
        | rev
}

canonicalize_path() {
    cat | xargs -I'{}' readlink -f "$dir/{}"
}

get_paths \
    | trim_path \
    | fzf \
    | canonicalize_path

