#!/bin/sh
export INFO='choose a power-off method with fzf popup'

~/scripts/cmd/require fzf systemctl hyprlock hyprctl || exit $?
~/scripts/cmd/require ~/scripts/cmd/terminal-popup || exit $?

# Kill any running instances
kill_recurse() {
    pid="$1"
    for child in $(pgrep -P "$pid"); do
        kill_recurse "$child"
    done
    kill -TERM "$pid" 2>/dev/null
}
for pid in $(pgrep -f 'powermenu'); do
    if [ ! "$pid" = $$ ]; then
        kill_recurse "$pid"
    fi
done

menu="\
 Cancel
 Suspend
 Shutdown
 Reboot
 Logout
 Lock"

answer="$(terminal-popup \
    "echo \"$menu\" \
        | fzf \
            --reverse \
            --highlight-line \
            --cycle \
            --margin=1" \
    || exit $?)"

try() {
    if ! $@; then
        notify-send "failed operation: $*"
    fi
}

case "$answer" in
    ' Shutdown') try systemctl poweroff ;;
    ' Reboot')   try systemctl reboot ;;
    ' Suspend')  try hyprlock & try systemctl suspend ;;
    ' Lock')     try hyprlock ;;
    ' Logout')   hyprctl dispatch exit ;;
    *) ;; # Ignore
esac

