#!/bin/sh
export INFO='show, find, or make Garfield comics (garf help)'

dir="$HOME/scripts/garf"

available='help | show | make | find | revise | transcribe | stats'

# Missing command
if [ ! "$1" ]; then
    echo 'garf: missing subcommand'
    echo "    available subcommands: $available"
    exit 1
fi

# Remove subcommand from $@
cmd="$1"
shift

case "$cmd" in
    # Help
    'help'|'h'|'--help'|'-h')
        echo 'garf: available subcommands'
        echo '    show:       display a comic'
        echo '    make:       make post data including formatted comic'
        echo '    find:       open all comics with given month and day, or post id'
        echo '    revise:     remake next old post'
        echo '    transcribe: add a transcription to a post'
        exit 0
        ;;

    # Public
    'show'|'s')
        "$dir/show" "$@"
        ;;
    'make'|'m')
        "$dir/make" "$@"
        ;;
    'find'|'f')
        "$dir/find" "$@"
        ;;
    'revise'|'r')
        "$dir/revise" "$@"
        ;;
    'transcribe'|'t')
        "$dir/transcribe" "$@"
        ;;
    'stats')
        "$dir/stats" "$@"
        ;;

    # Unlisted
    'sunday'|'sundays'|'su')
        "$dir/sundays" "$@"
        ;;

    # Private
    '+dir')
        "$dir/dir" "$@"
        ;;
    '+format')
        "$dir/format" "$@"
        ;;
    '+organize')
        "$dir/organize" "$@"
        ;;
    '+old')
        "$dir/old" "$@"
        ;;
    '+recent')
        "$dir/recent" "$@"
        ;;

    *)
        echo "garf: unknown subcommand: '$cmd'"
        echo "    available subcommands: $available"
        exit 1
        ;;
esac

