#!/bin/sh

dir="$HOME/scripts/garf"

available='help | show | make | find | date | date-all | error | revise'

# Missing command
if [ ! "$1" ]; then
    echo 'garf: missing subcommand'
    echo "    available subcommands: $available"
    exit 1
fi

# Remove subcommand from $@
cmd="$1"
shift

case "$cmd" in
    # Help
    'help'|'h'|'--help'|'-h')
        echo 'garf: available subcommands'
        echo '    show:     display a comic'
        echo '    make:     make post data including formatted comic'
        echo '    find:     open all comics with given month and day, or post id'
        echo '    date:     add date to existing post'
        echo '    date-all: add date to all posts with missing dates'
        echo '    error:    show next post with error'
        echo '    revise:   remake next post with error'
        exit 0
        ;;

    # Public
    'show'|'s')
        "$dir/show" "$@"
        ;;
    'make'|'m')
        "$dir/make" "$@"
        ;;
    'find'|'f')
        "$dir/find" "$@"
        ;;
    'date'|'d')
        "$dir/date" "$@"
        ;;
    'date-all'|'da')
        "$dir/date-all" "$@"
        ;;
    'error'|'e')
        "$dir/error" "$@"
        ;;
    'revise'|'e')
        "$dir/revise" "$@"
        ;;

    # Private
    '+format')
        "$dir/format" "$@"
        ;;
    '+organize')
        "$dir/organize" "$@"
        ;;

    *)
        echo "garf: unknown subcommand: '$cmd'"
        echo "    available subcommands: $available"
        exit 1
        ;;
esac

