#!/bin/sh
#~~~ show, find, or make Garfield comics (garf help)

dir="$HOME/scripts/garf"

available='help | show | make | find | | error | revise'

# Missing command
if [ ! "$1" ]; then
    echo 'garf: missing subcommand'
    echo "    available subcommands: $available"
    exit 1
fi

# Remove subcommand from $@
cmd="$1"
shift

case "$cmd" in
    # Help
    'help'|'h'|'--help'|'-h')
        echo 'garf: available subcommands'
        echo '    show:     display a comic'
        echo '    make:     make post data including formatted comic'
        echo '    find:     open all comics with given month and day, or post id'
        echo '    error:    show next post with error'
        echo '    revise:   remake next post with error'
        exit 0
        ;;

    # Public
    'show'|'s')
        "$dir/show" "$@"
        ;;
    'make'|'m')
        "$dir/make" "$@"
        ;;
    'find'|'f')
        "$dir/find" "$@"
        ;;
    'error'|'e')
        "$dir/error" "$@"
        ;;
    'revise'|'r')
        "$dir/revise" "$@"
        ;;

    # Unlisted
    'sunday'|'sundays'|'su')
        "$dir/sundays" "$@"
        ;;

    # Private
    '+dir')
        "$dir/dir" "$@"
        ;;
    '+format')
        "$dir/format" "$@"
        ;;
    '+organize')
        "$dir/organize" "$@"
        ;;

    *)
        echo "garf: unknown subcommand: '$cmd'"
        echo "    available subcommands: $available"
        exit 1
        ;;
esac

