#!/bin/sh
export INFO='kill all unattatched (orphaned) tmux sessions'

count=0
# Get list of sessions
for session in $(tmux list-sessions -F '#{session_name}:#{session_attached}'); do
    # Split session into name and attached count
        name="${session%:*}"
    attached="${session#*:}"
    printf "$name -- $attached"
    # Kill if nothing is attached
    if [ "$attached" = 0 ]; then
        printf " KILL!"
        tmux kill-session -t "$name"
        count=$((count + 1))
    fi
    echo
done

if [ "$count" -gt 0 ]; then
    [ "$count" = 1 ] || s='s'
    notify-send -t 1500 "Killed $count orphan$s."
else
    notify-send -t 1500 "No orphans to kill."
    exit 1
fi
