#!/bin/sh

default() {
    xdo close
}

class="$(xdotool getactivewindow getwindowclassname)"

case "$class" in
    # Kill background process as well
    # This program is a scratchpad
    'ArmCord')
        default
        killall 'armcord'
        ;;
    'vesktop')
        default
        killall 'electron'
        ;;
    'TelegramDesktop')
        default
        killall 'telegram-desktop'
        ;;
    'Windscribe2')
        killall -KILL 'windscribe' # Close quickly (maybe this is bad?)
        ;;

    # Add custom rules here...

    *) default ;;
esac

