#!/bin/sh
#~~~ make a shell script, with shebang, and executable permission

if [ ! "$1" ]; then
    echo 'mkscript: no filename given.'
    exit 1
fi

if [ -e "$1" ]; then
    echo "mkscript: file or directory already exists named '$1'"
    exit 1
fi

# Create file
printf '#!/bin/sh\n#~~~ \n\n' > "$1"
# Set as executable
chmod +x "$1"

