#!/bin/sh
export INFO='index all files in movies directory'

~/scripts/cmd/require tree || exit $?

# Location of movies folder 
drive="/run/media/$(whoami)/MOVIES/Movies"
# Filepath of movies list backup
list_copy="$HOME/docs/movies.txt"
# Location of semdir folder
semdir="$HOME/docs/misc/semdir"

cd "$drive" || exit 1

tree . --filesfirst > '.meta/movies.txt' || exit 1
cp '.meta/movies.txt' "$list_copy"       || exit 1
cp "$semdir/README.md" '.meta/SEMDIR.md' || exit 1

echo 'Done.'

