#!/bin/sh
export INFO='print random name for Neorg note file, with date'

~/scripts/cmd/require ~/scripts/cmd/random-name || exit $?

# Directory of notes
dir="$HOME/docs/notes"

# Create folder if doesn't exist
if [ ! -d "$dir" ]; then
    mkdir "$dir" || exit 1
fi

# Get name with date and random string
now=$(date +'%y%m%d')
id=$(~/scripts/cmd/random-name)
name="${now}_${id}"

# Full path of non-existant file
echo "$dir/$name"

