#!/bin/sh
export INFO='print random name for note file, with date'

~/scripts/cmd/require namegen || exit $?

# Directory of notes
dir="$HOME/docs/notes"

# Create folder if doesn't exist
if [ ! -d "$dir" ]; then
    mkdir "$dir" || exit 1
fi

# Get name with date and random string
name=$(namegen '@F_%A-%N')

# Full path of non-existant file
echo "$dir/$name"

