#!/bin/sh
INFO='clear all cache for nvim'

# All cache
trash ~/.cache/nvim
trash ~/.local/share/nvim
trash ~/.local/state/nvim
# Packer
trash ~/dotfiles/nvim/.config/nvim/plugin/packer_compiled.lua
# Lazy
trash ~/dotfiles/nvim/.config/nvim/lazy-lock.json

