#!/bin/sh
export INFO='open a file with program based on mimetype'

~/scripts/cmd/require devour xdg-open || exit $?

[ -n "$1" ] || exit 0

case "$(file --mime-type --brief --dereference "$@")" in

    # Do not replace window for these
    image/svg* )
        inkscape "$@"
        ;;
    image/x-xcf )
        gimp "$@"
        ;;

    image/* )
        devour nsxiv "$@"
        ;;

    video/* | audio/* )
        devour mpv "$@"
        ;;

    application/pdf | application/postscript )
        devour zathura "$@"
        ;;

    *)
        echo 'open: using xdg-open fallback.' >&2
        xdg-open "$@" || exit $?
        ;;
esac

