#!/bin/sh
export INFO='choose a power-off method with Rofi dialog'

~/scripts/cmd/require rofi systemctl betterlockscreen i3-msg
# TODO: Use wayland-compatible lockscreen

MONITOR='eDP-1'

menu="\
 Cancel
 Suspend
 Shutdown
 Reboot
 Logout
 Lock"

# Disable cache file to use consistent order
answer="$(echo "$menu" \
    | wofi --show dmenu \
        --prompt 'Powermenu' \
        --monitor $MONITOR \
        --cache-file=/dev/null
)"

case "$answer" in
    ' Shutdown') systemctl poweroff ;;
    ' Reboot')   systemctl reboot ;;
    ' Suspend')  systemctl suspend ;;
    ' Lock')     betterlockscreen -l ;;
    ' Logout')   hyprctl dispatch exit ;;
    *) ;;
esac

