#!/bin/sh
export INFO='choose a power-off method with Rofi dialog'

~/scripts/cmd/require kitty fzf systemctl hyprlock hyprctl

CLASS='popup'

menu="\
 Cancel
 Suspend
 Shutdown
 Reboot
 Logout
 Lock"

fifo_path="$(mktemp --dry-run -p /tmp powermenu.XXXX)"
mkfifo "$fifo_path"

# Send output of terminal command to FIFO, for parent process to read
kitty --class $CLASS \
    --override font_size=12 \
    -- sh -c "
    echo \"$menu\" \
        | fzf \
            --reverse \
            --highlight-line \
            --cycle \
            --margin=1 \
        >> \"$fifo_path\"
    " &

answer="$(cat "$fifo_path")"
rm -f "$fifo_path"

try() {
    $@
    if [ $? -ne 0 ]; then
        notify-send "failed operation: $@"
    fi
}

case "$answer" in
    ' Shutdown') try systemctl poweroff ;;
    ' Reboot')   try systemctl reboot ;;
    ' Suspend')  try hyprlock & try systemctl suspend ;;
    ' Lock')     try hyprlock ;;
    ' Logout')   hyprctl dispatch exit ;;
    *) ;;
esac

