#!/bin/sh
export INFO='choose a power-off method with Rofi dialog'

~/scripts/cmd/require wofi systemctl hyprlock hyprctl

MONITOR='eDP-1'

menu="\
 Cancel
 Suspend
 Shutdown
 Reboot
 Logout
 Lock"

# Disable cache file to use consistent order
answer="$(echo "$menu" \
    | wofi --show dmenu \
        --prompt 'Powermenu' \
        --monitor $MONITOR \
        --cache-file=/dev/null
)"

try() {
    $@
    if [ $? -ne 0 ]; then
        notify-send "failed operation: $@"
    fi
}

case "$answer" in
    ' Shutdown') try systemctl poweroff ;;
    ' Reboot')   try systemctl reboot ;;
    ' Suspend')  try hyprlock & try systemctl suspend ;;
    ' Lock')     try hyprlock ;;
    ' Logout')   hyprctl dispatch exit ;;
    *) ;;
esac

