#!/bin/sh
export INFO='rename all files in current directory, using Neovim'

temp_file='/tmp/rename-all'

for old in *; do
    printf "'%s' " "$old"
    read -r _

    echo "$old" > "$temp_file"
    "$EDITOR" "$temp_file" || continue
    new="$(cat "$temp_file")"

    if [ "$new" = "$old" ]; then
        continue
    fi

    mv "$old" "$new" || exit 1
done

