#!/bin/sh
export INFO='check if commands or binaries are installed'

code=199

missing=''
for cmd in "$@"; do
    if [ ! -x "$(command -v "$cmd")" ]; then
        missing="$missing $cmd"
    fi
done

if [ -n "$missing" ]; then
    echo 'require: missing dependencies:'
    printf '\033[1m'
    echo "$missing" | sed 's/ /\n  /g' | tail -n+2
    printf '\033[0m'
    exit "$code"
fi

