#!/bin/sh
export INFO='check all user scripts for bashisms or linting errors'

# Get location of scripts folder
scripts="$(readlink -f "$(dirname "$0")/..")"

# Check each file in directory
check_dir() {
    for file in "$1/"*; do 
        shellcheck "$file" &
    done
}

check_dir "$scripts/cmd"
check_dir "$scripts/garf"

