#!/bin/sh
export INFO='rename all files in directory to random strings, preserving file extensions'

~/scripts/cmd/require namegen || exit $?

dir="$1"
if [ -n "$dir" ]; then
    cd "$dir" || exit 1
fi

for file in *; do
    [ -d "$file" ] && continue;
    ext="${file#*.}"
    name="$(namegen '%8l')"
    mv "$file" "$name.$ext" || exit 1
done

