#!/bin/sh
export INFO='prints size of file or directory in SI-prefixed bytes'

file="$1"

if [ -z "$file" ]; then
    echo 'sizeof: missing file argument.'
    exit 1
fi
if [ ! -e "$file" ]; then
    echo 'sizeof: no such file or directory.'
    exit 2
fi

# -s    only show total
# -b    --block-size=1 
# --si  use powers of 1000, not 1024

size="$(du -sb --si "$file" | awk '{print $1}')"

printf "%sB\n" "$size" 

