#!/bin/sh
export INFO='download all songs from a particular Spotify playlist'

~/scripts/cmd/require notify-send || exit 1

# Location of spotdl binary
if [ -n "$1" ]; then
    spotdl="$1"
else
    spotdl='spotdl'
    ~/scripts/cmd/require spotdl || exit 1
fi

# Directory to download to
location="$HOME/music/songs"
# Link to playlist to download
playlist='https://open.spotify.com/playlist/6lE0EKzv2S2S2SUHIbUDbh?si=19822f08519846b8'
# Filename of track
trackname='{list-position} {title} - {artists}'

# Confirm
echo 'Remove and redownload all songs'
printf 'Are you sure? [Y/n] '

# Return if input was not 'Y' or blank (enter key)
read -r confirm
case "$confirm" in
    'y'|'Y'|'') ;;
    *)
        echo 'Cancelled.'
        exit 0
        ;;
esac

# Remove old folder
if [ -d "$location" ]; then
    trash "$location"
fi
# Create new folder
mkdir -p "$location"
cd "$location" || exit 1
# Downloads songs to folder, with formatted filename
"$spotdl" "$playlist" --output "$trackname" || exit 1
notify-send 'Spotify download complete.'

