#!/bin/sh

# TODO: info
# TODO: dependencies

# TODO(refactor): Try to read from fd

fifo_path="$(mktemp --dry-run -p /tmp popup.XXXX)"
mkfifo "$fifo_path"

# Send output of terminal command to FIFO, for parent process to read
foot --app-id 'popup' \
    -- sh -c "$* >> \"$fifo_path\"" \
    &

cat "$fifo_path"
rm -f "$fifo_path"

