#!/bin/sh
export INFO='change volume or brightness, with notification'

~/scripts/cmd/require pactl brightnessctl dunstify

# Note: `brightnessctl` can be replaced with `xbacklight`, but this requires
# modifying `/etc/sudoers` to allow `xbacklight` to run as root without a
# password.

# Control options
step_volume=5
step_brightness=5
volume_max=100
# Notification options
bar_color="#7f7fff"
timeout=1000
dunst_id="2593"

show_help() {
    cat << EOF
$(basename "$0"): $INFO
    v+  Increase volume
    v-  Decrease volume
    vm  Mute/unmute volume
    b+  Increase brightness
    b-  Decrease brightness
EOF
}

# Only supports mono-audio
get_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ \
        | grep -Po '[0-9]+%' | sed 's/%$//' | head -n1
}

# Returns 0 if muted, 1 if unmuted
is_mute() {
    ! pactl get-sink-mute @DEFAULT_SINK@ | grep -q 'Mute: no'
}

get_brightness() {
    value=$(brightnessctl get)
    max=$(brightnessctl max)
    percent=$((100 * value / max))
    echo "$percent"
}

notify() {
    value="$1"
    icon="$2"
    dunstify \
        "$icon $value%" \
        --icon none \
        --timeout "$timeout" \
        --replace "$dunst_id" \
        --urgency normal \
        --hints "int:value:$value" \
        --hints "string:hlcolor:$bar_color"
}

notify_volume() {
    value=$(get_volume)
    if [ "$value" -eq 0 ] || is_mute ; then
        icon=''
    elif [ "$value" -lt 50 ]; then
        icon=''
    else
        icon=''
    fi
    notify "$value" "$icon"
}

notify_brightness() {
    value=$(get_brightness)
    notify "$value" ''
}

command="$1"
case "$command" in

    v+)
        # Unmute
        pactl set-sink-mute @DEFAULT_SINK@ 0
        value=$(get_volume)
        # Increase or set to max value
        if [ $(( $value + $step_volume )) -ge "$volume_max" ]; then
            pactl set-sink-volume @DEFAULT_SINK@ "$volume_max%"
        else
            pactl set-sink-volume @DEFAULT_SINK@ "+$step_volume%"
        fi
        notify_volume
        ;;
    v-)
        pactl set-sink-volume @DEFAULT_SINK@ "-$step_volume%"
        notify_volume
        ;;
    vm)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        notify_volume
        ;;

    b+)
        brightnessctl set "+$step_brightness% "
        notify_brightness
        ;;
    b-)
        brightnessctl set "$step_brightness%-"
        notify_brightness
        ;;

    h|help|-h|--help)
        show_help
        ;;
    *)
        show_help
        exit 1
        ;;

esac

