#!/bin/sh
export INFO='change volume or brightness, with notification'

~/scripts/cmd/require bc pactl wpctl brightnessctl dunstify
# TODO: Implement `mt` with `wpctl` (removes `pactl` dependency)

# Note: `brightnessctl` can be replaced with `xbacklight`, but this requires
# modifying `/etc/sudoers` to allow `xbacklight` to run as root without a
# password.

# Control options
STEP_VOLUME=5
STEP_BRIGHTNESS=5
VOLUME_MAX=100
# Notification options
BAR_COLOR="#7f7fff"
TIMEOUT=1000
DUNST_ID="2593"
# Icons
ICON_VOLUME_MUTE=''
ICON_VOLUME_LOW=''
ICON_VOLUME_HIGH=''
ICON_BRIGHTNESS=''
ICON_MICROPHONE_MUTE=''
ICON_MICROPHONE_ON=''

show_help() {
    cat << EOF
$(basename "$0"): $INFO
    v+  Increase volume
    v-  Decrease volume
    vm  Mute/unmute volume
    b+  Increase brightness
    b-  Decrease brightness
    mt Toggle microphone
EOF
}

# Returns 0 if muted, 1 if unmuted
is_mute() {
    ! wpctl get-volume @DEFAULT_SINK@ | grep -q '[MUTED]'
}

# Returns 0 if ALL microphones are disabled, otherwise 1
is_any_mic_enabled() {
    pactl list sources | grep -q 'Mute: no'
}

to_percent() {
    echo "$1 * 100" \
        | bc \
        | sed 's/\.00$//'
}

# Only supports mono-audio
get_volume() {
    volume=$(wpctl get-volume @DEFAULT_SINK@ \
        | awk '{print $2}')
    to_percent "$volume"
}

get_brightness() {
    value=$(brightnessctl get)
    max=$(brightnessctl max)
    percent=$((100 * value / max))
    echo "$percent"
}

# If any microphones are enabled, then disable all
# Else, enable all
toggle_all_mics() {
    if is_any_mic_enabled;
        then new_state=1 # Mute / disable
        else new_state=0 # Unmute / enable
    fi
    for source in $(pactl list short sources | awk '{print $1}'); do
        pactl set-source-mute "$source" "$new_state"
    done
}

notify() {
    text="$1"
    icon="$2"
    shift 2
    dunstify \
        "$icon $text" \
        --icon none \
        --timeout "$TIMEOUT" \
        --replace "$DUNST_ID" \
        --urgency normal \
        "$@"
}

notify_progress() {
    value="$1"
    icon="$2"
    notify "$value%" "$icon" \
        --hints "int:value:$value" \
        --hints "string:hlcolor:$BAR_COLOR"
}

notify_volume() {
    value=$(get_volume)
    if [ "$value" -eq 0 ] || is_mute; then
        icon="$ICON_VOLUME_MUTE"
    elif [ "$value" -lt 50 ]; then
        icon="$ICON_VOLUME_LOW"
    else
        icon="$ICON_VOLUME_HIGH"
    fi
    notify_progress "$value" "$icon"
}

notify_brightness() {
    value=$(get_brightness)
    notify_progress "$value" "$ICON_BRIGHTNESS"
}

notify_microphone() {
    if is_any_mic_enabled; then
        text='Microphone ENABLED'
        icon="$ICON_MICROPHONE_ON"
    else
        text='Microphone disabled'
        icon="$ICON_MICROPHONE_MUTE"
    fi
    notify "$text" "$icon"
}

command="$1"
case "$command" in

    v+)
        wpctl set-mute @DEFAULT_SINK@ 0
        value=$(get_volume)
        # Increase or set to max value
        if [ $(( value + STEP_VOLUME )) -ge "$VOLUME_MAX" ];
            then wpctl set-volume @DEFAULT_SINK@ "$VOLUME_MAX%"
            else wpctl set-volume @DEFAULT_SINK@ "$STEP_VOLUME%+"
        fi
        notify_volume
        ;;
    v-)
        wpctl set-mute @DEFAULT_SINK@ 0
        wpctl set-volume @DEFAULT_SINK@ "$STEP_VOLUME%-"
        notify_volume
        ;;
    vm)
        wpctl set-mute @DEFAULT_SINK@ toggle
        notify_volume
        ;;

    b+)
        brightnessctl set "+$STEP_BRIGHTNESS% "
        notify_brightness
        ;;
    b-)
        brightnessctl set "$STEP_BRIGHTNESS%-"
        notify_brightness
        ;;

    mt)
        toggle_all_mics
        notify_microphone
        ;;

    h|help|-h|--help)
        show_help
        ;;
    *)
        show_help
        exit 1
        ;;

esac

