#!/bin/sh
#~~~ print the help comment for a user script

dir="$HOME/scripts/cmd"
name="$1"

# Not a file, or a script
if [ ! "$name" ]; then
    echo 'whatscript: no script name given'
    exit 1
fi
if [ ! -f "$dir/$name" ]; then
    echo "whatscript: '$name' is not a user script"
    exit 1
fi

# Help comment identifier
ident='^#~~~ '

# Find message
# First line beginning with identifier
msg=$(
    < "$dir/$name" \
    grep "$ident" | head -n 1 |\
    sed "s/$ident//"
)

# Print message if found
if [ "$msg" ]; then
    echo "$name: $msg"
else
    echo "$name: (apparently was not worth documenting)"
fi

