#!/bin/sh

id="$1"

if [ ! "$id" ]; then
    echo 'garf find-post: no id given.'
    exit 1
fi

src="$HOME/pics/garfeo/posts/$id/esperanto.png"

if [ ! -f "$src" ]; then
    echo 'garf find-post: post not found with that id.'
    exit 1
fi

echo 'Opening image...'
display "$src"

printf 'Enter date (mm-dd): '
read -r date

echo 'Find comics with that date...'
~/scripts/garf/run find-date "$date" || exit 1

